### ISSUE TITLE
MediaExtractor doesnt work for an HTTP url 

### ISSUE THREAD

**Issue by rahulrj** [cedricfung/MediaCodecDemo#9]
The code works fine for a video loaded from sd-card, but it fails with the following error when i try to load a video from a URL. One of the URLs i tried is this
http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4

I am running the code on Android M.

```
14646-14765/io.vec.demo.mediacodec I/MediaHTTPConnection: proxyName: 0.0.0.0 0
 E/NuCachedSource2: source returned error -1, 0 retries left
14646-14752/io.vec.demo.mediacodec E/QComExtractorFactory: Sniff FAIL :: coundn't pull enough data for sniffing
14646-14752/io.vec.demo.mediacodec W/System.err: java.io.IOException: Failed to instantiate extractor.
14646-14752/io.vec.demo.mediacodec W/System.err:     at android.media.MediaExtractor.nativeSetDataSource(Native Method)
14646-14752/io.vec.demo.mediacodec W/System.err:     at android.media.MediaExtractor.setDataSource(MediaExtractor.java:182)
14646-14752/io.vec.demo.mediacodec W/System.err:     at io.vec.demo.mediacodec.DecodeActivity$PlayerThread.run(DecodeActivity.java:65)
```

**Comment by sandeepmvd** [comment]
I have limited experience with mediacodec. But as explained in the official documentation, the data source should be able to provide direct frames. Http video data(if H.264 stream) will be in the form of NAL units(Network abstraction layer). These are fragment parts of a single frame. You can either write NAL parser to reconstruct the complete frames and then feed it to the Mediacodec or you can directly use Mediaplayer class in android which supports http streaming.
